Update noor-dep.yml

diff --git a/.github/workflows/noor-dep.yml b/.github/workflows/noor-dep.yml
--- a/.github/workflows/noor-dep.yml
+++ b/.github/workflows/noor-dep.yml
@@ -25,9 +25,9 @@ jobs:
         # run: |  
         #   sudo apt-get update
         #   sudo apt-get install -y gh jq
-      - name: Authenticate GitHub CLI
-        run: |
-          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
+      # - name: Authenticate GitHub CLI
+      #   run: |
+      #     echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
           
       - name: Process Dependabot PRs with no comments
         env:
@@ -77,9 +77,9 @@ jobs:
             
             # 4. Approve the PR
             echo "  Approving the PR."
-            # gh pr review $PR_NUM --approve -b "Automatic approval."
+             gh pr review $PR_NUM --approve -b "Automatic approval."
 
             # 5. Enable auto-merge
             echo "  Enabling auto-merge."
-            # gh pr merge $PR_NUM --auto --squash || echo "  Warning: Could not enable auto-merge for PR #$PR_NUM."
+             gh pr merge $PR_NUM --auto --squash || echo "  Warning: Could not enable auto-merge for PR #$PR_NUM."
           done
