a

diff --git a/.github/workflows/Trivy-final-demo.yml b/.github/workflows/Trivy-final-demo.yml
--- a/.github/workflows/Trivy-final-demo.yml
+++ b/.github/workflows/Trivy-final-demo.yml
@@ -35,25 +35,34 @@ jobs:
             severity: 'HIGH,CRITICAL'
             trivyignores: './.trivyignore'
             exit-code: '1'  # Fail the job if vulnerabilities are found
-            output: 'trivy-result.txt'
+            output: 'trivy.txt'
 
 
-      - name: Format Trivy scan result
+      - name: Format Trivy Output for PR Comment
+        id: trivy_comment
         run: |
-          if [ -s trivy-result.txt ]; then
-            echo -e "## 🔍 Trivy Scan Results\n<details><summary>Click to expand</summary>\n\n\`\`\`\n$(cat trivy-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
-          else
-            echo "## ✅ No vulnerabilities found." > formatted-trivy-result.md
-          fi
+            if [[ -s trivy.txt ]]; then
+              {
+                echo "### 🔍 Trivy IaC Scan Report"
+                echo "<details><summary>Click to expand</summary>"
+                echo ""
+                echo '```terraform'
+                cat trivy.txt
+                echo '```'
+                echo "</details>"
+              } > trivy_comment.txt
+            else
+              echo "✅ No issues found in Trivy scan." > trivy_comment.txt
+            fi
 
       - name: Comment on PR with Trivy Scan Results
         uses: peter-evans/create-or-update-comment@v5
         with:
             issue-number: ${{ github.event.pull_request.number }}
-            body-file: formatted-trivy-result.md
+            body-file: trivy_comment.txt
 
-      - name: Fail if Trivy found high/critical issues
+      - name: Fail the job if Trivy finds Misconfiguration or warnings
         if: steps.trivy.outcome == 'failure'
         run: |
-          echo "❌ Trivy found high or critical issues. Failing the job."
-          exit 1
+            echo "❌ Trivy found Low Medium high or critical issues. Failing the job."
+            exit 1
